global:
  # How frequently to scrape targets by default.
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor-worker1'
    static_configs:
      - targets: ['192.168.142.144:8080']

  - job_name: 'cadvisor-worker2'
    static_configs:
      - targets: ['192.168.142.143:8080']
  - job_name: 'kube-metrics'
    static_configs:
      - targets: ['192.168.142.137:30000']