apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.15.0
  name: kube-state-metrics
  namespace: kube-system
spec:
  type: NodePort # Définit le type de service comme NodePort
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
    nodePort: 30000 # Optionnel : Spécifie un port fixe sur les nœuds (entre 30000 et 32767). Si omis, un port aléatoire est attribué.
  - name: telemetry
    port: 8081
    targetPort: telemetry
    nodePort: 30000 # Optionnel : Spécifie un port fixe sur les nœuds.
  selector:
    app.kubernetes.io/name: kube-state-metrics