- name: Pre Install
  hosts: all
  become: true
  tasks:
  - name: Mise à jour de la liste des paquets
    apt:
      update_cache: true
      upgrade: dist
  - name: Installer python3 et python3-pip
    apt:
      name:
      - python3
      - python3-pip
  - name: Charger le module br_netfilter
    modprobe:
      name: br_netfilter
      state: present
  - name: Mise à jour de la liste des paquets
    apt:
      update_cache: true
      upgrade: dist
