- name: Setup Hosts
  hosts: all
  become: true
  tasks:

############################################################
# Ajouter les entrées des hôtes et le nom de domaine dans le fichier /etc/hosts
############################################################
  - name: Définir les entrées des hôtes + nom de domaine du site web
    blockinfile:
      path: /etc/hosts
      block: |
        192.168.142.137 Master
        192.168.142.144 Worker1
        192.168.142.143 Worker2
        192.168.142.137 mon-site-local.test
      backup: true

############################################################
# Définir le nom d’hôte pour la VM Master
############################################################
  - name: Définir le nom d'hôte pour la VM Master
    hostname:
      name: Master
    when: inventory_hostname == '192.168.142.137'

############################################################
# Définir le nom d’hôte pour la VM Worker1
############################################################
  - name: Définir le nom d'hôte pour la VM Worker 1
    hostname:
      name: Worker1
    when: inventory_hostname == '192.168.142.144'

############################################################
# Définir le nom d’hôte pour la VM Worker2
############################################################
  - name: Définir le nom d'hôte pour la VM Worker 2
    hostname:
      name: Worker2
    when: inventory_hostname == '192.168.142.143'

############################################################
# Installer Python 3 et pip (prérequis pour d'autres tâches Ansible)
############################################################
  - name: Installer python3 et python3-pip
    apt:
      name:
        - python3
        - python3-pip

############################################################
# Charger le module noyau br_netfilter (nécessaire pour Kubernetes)
############################################################
  - name: Charger le module br_netfilter
    modprobe:
      name: br_netfilter
      state: present

############################################################
# Mettre à jour la liste des paquets et effectuer une mise à jour complète
############################################################
  - name: Mise à jour de la liste des paquets
    apt:
      update_cache: true
      upgrade: dist
