apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-doc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site-doc
  template:
    metadata:
      labels:
        app: site-doc
    spec:
      containers:
      - name: site
        image: valouze14/valouze14:latest
        ports:
        - containerPort: 80
        - containerPort: 443