apiVersion: v1
kind: Service
metadata:
  name: site-doc-service # Nom du service, distinct de celui du pod
spec:
  selector:
    app: site-doc
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8090 # Le port sur lequel le service écoutera à l'intérieur du cluster
      targetPort: 8090 # Le port sur lequel votre application écoute à l'intérieur du pod (port 80 de votre conteneur)
      nodePort: 30080 # Un port entre 30000 et 32767. Choisissez-en un disponible.
    - name: https
      protocol: TCP
      port: 4443 # Le port sur lequel le service écoutera à l'intérieur du cluster pour HTTPS
      targetPort: 4443 # Le port sur lequel votre application écoute à l'intérieur du pod (port 443 de votre conteneur)
      nodePort: 30443 # Autre port disponible pour HTTPS, par exemple 30443